"""Migration script template."""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bc475af6a8b'
down_revision: Union[str, None] = 'df217a82a9d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_user_sessions_active', 'user_sessions', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.add_column('user_profiles', sa.Column('two_factor_enabled', sa.Boolean(), nullable=False))
    op.add_column('user_profiles', sa.Column('login_notifications', sa.Boolean(), nullable=False))
    op.add_column('user_profiles', sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('user_profiles', sa.Column('privacy_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('user_profiles', sa.Column('preferred_currency', sa.String(length=10), nullable=False))
    op.add_column('user_profiles', sa.Column('language', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'language')
    op.drop_column('user_profiles', 'preferred_currency')
    op.drop_column('user_profiles', 'privacy_settings')
    op.drop_column('user_profiles', 'notification_preferences')
    op.drop_column('user_profiles', 'login_notifications')
    op.drop_column('user_profiles', 'two_factor_enabled')
    op.drop_index('idx_user_sessions_user_id', table_name='user_sessions')
    op.drop_index('idx_user_sessions_active', table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
