"""Migration script template."""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df217a82a9d4'
down_revision: Union[str, None] = 'webhook_events_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # RESILIENCE: Ensure types exist before creating tables that use them
    # But don't try to re-create if they already exist
    connection = op.get_bind()

    enums = [
        ('currency', ['USD', 'GHS', 'GBP', 'EUR', 'CAD', 'AUD']),
        ('payoutstatus', ['PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED']),
        ('verificationcategory', ['IDENTITY', 'BUSINESS', 'PROFESSIONAL', 'BUYER', 'SELLER', 'PROOF_OF_FUNDS', 'ASSET_OWNERSHIP', 'FINANCIAL', 'TRAFFIC', 'TECHNICAL']),
        ('verificationstatus', ['NOT_STARTED', 'IN_PROGRESS', 'ACTION_REQUIRED', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', 'EXPIRED', 'SUSPENDED']),
        ('dataaccessrequeststatus', ['PENDING_NDA', 'NDA_SIGNED', 'PENDING_VERIFICATION', 'PENDING_SELLER_REVIEW', 'APPROVED', 'REJECTED', 'REVOKED', 'EXPIRED', 'CANCELLED']),
        ('disputestatus', ['OPEN', 'UNDER_REVIEW', 'WAITING_FOR_BUYER', 'WAITING_FOR_SELLER', 'ESCALATED', 'RESOLVED', 'CLOSED']),
        ('buyertier', ['BASIC', 'VERIFIED', 'FUNDED', 'TRUSTED']),
        ('saletype', ['BUY_NOW', 'AUCTION', 'NEGOTIATION']),
        ('listingvettingstatus', ['DRAFT', 'SUBMITTED', 'AUTOMATED_REVIEW', 'HUMAN_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'PUBLISHED', 'SUSPENDED', 'SOLD', 'ARCHIVED', 'REJECTED'])
    ]

    for enum_name, values in enums:
        res = connection.execute(sa.text(f"SELECT 1 FROM pg_type WHERE typname = '{enum_name}'")).fetchone()
        if not res:
            postgresql.ENUM(*values, name=enum_name).create(connection)

    op.create_table('acquisition_guides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acquisition_guides_slug'), 'acquisition_guides', ['slug'], unique=True)
    op.create_table('broker_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('specialties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('verified_broker', sa.Boolean(), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', postgresql.ENUM('USD', 'GHS', 'GBP', 'EUR', 'CAD', 'AUD', name='currency', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='payoutstatus', create_type=False), nullable=False),
    sa.Column('payout_method', sa.String(length=50), nullable=False),
    sa.Column('destination_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payout_positive_amount'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payouts_status', 'payouts', ['status'], unique=False)
    op.create_index('idx_payouts_user_id', 'payouts', ['user_id'], unique=False)
    op.create_table('user_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', postgresql.ENUM('IDENTITY', 'BUSINESS', 'PROFESSIONAL', 'BUYER', 'SELLER', 'PROOF_OF_FUNDS', 'ASSET_OWNERSHIP', 'FINANCIAL', 'TRAFFIC', 'TECHNICAL', name='verificationcategory', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'ACTION_REQUIRED', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', 'EXPIRED', 'SUSPENDED', name='verificationstatus', create_type=False), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', name='uq_user_verification_category')
    )
    op.create_table('client_representations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('broker_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('commission_agreement', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['broker_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_room_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.Column('handover_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_url', sa.String(length=500), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_room_id'], ['deal_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_access_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING_NDA', 'NDA_SIGNED', 'PENDING_VERIFICATION', 'PENDING_SELLER_REVIEW', 'APPROVED', 'REJECTED', 'REVOKED', 'EXPIRED', 'CANCELLED', name='dataaccessrequeststatus', create_type=False), nullable=False),
    sa.Column('nda_signature_id', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nda_signature_id'], ['nda_signatures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['revoked_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'buyer_id', name='uq_listing_buyer_access')
    )
    op.create_index('idx_data_access_status', 'data_access_requests', ['status'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_room_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'UNDER_REVIEW', 'WAITING_FOR_BUYER', 'WAITING_FOR_SELLER', 'ESCALATED', 'RESOLVED', 'CLOSED', name='disputestatus', create_type=False), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_room_id'], ['deal_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_webhook_events_processed_at'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_provider_event_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_transaction_id'), table_name='webhook_events')
    op.drop_table('webhook_events')

    # 1. Add columns as nullable first
    op.add_column('buyer_profiles', sa.Column('tier', postgresql.ENUM('BASIC', 'VERIFIED', 'FUNDED', 'TRUSTED', name='buyertier', create_type=False), nullable=True))
    op.add_column('buyer_profiles', sa.Column('standing_score', sa.Integer(), nullable=True))
    op.add_column('buyer_profiles', sa.Column('monthly_unlock_limit', sa.Integer(), nullable=True))
    op.add_column('buyer_profiles', sa.Column('used_unlocks_this_month', sa.Integer(), nullable=True))

    op.add_column('listings', sa.Column('sale_type', postgresql.ENUM('BUY_NOW', 'AUCTION', 'NEGOTIATION', name='saletype', create_type=False), nullable=True))
    op.add_column('listings', sa.Column('starting_price', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('listings', sa.Column('reserve_price', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('listings', sa.Column('current_bid', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('listings', sa.Column('bid_count', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('auction_ends_at', sa.DateTime(), nullable=True))
    op.add_column('listings', sa.Column('require_nda', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('require_identity_verification', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('require_proof_of_funds', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('require_seller_approval', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('require_verified_buyer', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('access_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('listings', sa.Column('contracted_at', sa.DateTime(), nullable=True))
    op.add_column('listings', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))

    # 2. Fill defaults for existing rows
    op.execute("UPDATE buyer_profiles SET tier = 'BASIC', standing_score = 100, monthly_unlock_limit = 10, used_unlocks_this_month = 0")
    op.execute("UPDATE listings SET sale_type = 'NEGOTIATION', bid_count = 0, require_nda = true, require_identity_verification = true, require_proof_of_funds = false, require_seller_approval = true, require_verified_buyer = false")

    # 3. Set columns as NOT NULL
    op.alter_column('buyer_profiles', 'tier', nullable=False)
    op.alter_column('buyer_profiles', 'standing_score', nullable=False)
    op.alter_column('buyer_profiles', 'monthly_unlock_limit', nullable=False)
    op.alter_column('buyer_profiles', 'used_unlocks_this_month', nullable=False)

    op.alter_column('listings', 'sale_type', nullable=False)
    op.alter_column('listings', 'bid_count', nullable=False)
    op.alter_column('listings', 'require_nda', nullable=False)
    op.alter_column('listings', 'require_identity_verification', nullable=False)
    op.alter_column('listings', 'require_proof_of_funds', nullable=False)
    op.alter_column('listings', 'require_seller_approval', nullable=False)
    op.alter_column('listings', 'require_verified_buyer', nullable=False)

    # 4. Map and cast status column safely
    op.alter_column('listings', 'status', type_=sa.Text())
    op.execute("UPDATE listings SET status = 'PUBLISHED' WHERE status = 'ACTIVE'")
    op.execute("UPDATE listings SET status = 'DRAFT' WHERE status NOT IN ('SUBMITTED', 'AUTOMATED_REVIEW', 'HUMAN_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'PUBLISHED', 'SUSPENDED', 'SOLD', 'ARCHIVED', 'REJECTED')")

    op.alter_column('listings', 'status',
               type_=sa.Enum('DRAFT', 'SUBMITTED', 'AUTOMATED_REVIEW', 'HUMAN_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'PUBLISHED', 'SUSPENDED', 'SOLD', 'ARCHIVED', 'REJECTED', name='listingvettingstatus', create_type=False),
               postgresql_using='status::listingvettingstatus')
    op.create_index('idx_listings_search_vector', 'listings', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('nda_signatures', sa.Column('full_legal_name', sa.String(length=255), nullable=True))
    op.add_column('nda_signatures', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('nda_signatures', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('nda_signatures', sa.Column('signature_data', sa.Text(), nullable=True))
    op.add_column('nda_signatures', sa.Column('signature_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nda_signatures', 'signature_type')
    op.drop_column('nda_signatures', 'signature_data')
    op.drop_column('nda_signatures', 'company')
    op.drop_column('nda_signatures', 'email')
    op.drop_column('nda_signatures', 'full_legal_name')
    op.drop_index('idx_listings_search_vector', table_name='listings', postgresql_using='gin')
    op.alter_column('listings', 'status',
               existing_type=sa.Enum('DRAFT', 'SUBMITTED', 'AUTOMATED_REVIEW', 'HUMAN_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'PUBLISHED', 'SUSPENDED', 'SOLD', 'ARCHIVED', 'REJECTED', name='listingvettingstatus'),
               type_=postgresql.ENUM('DRAFT', 'PENDING_REVIEW', 'ACTIVE', 'SOLD', 'EXPIRED', 'REJECTED', 'SUSPENDED', 'ARCHIVED', name='listingstatus'),
               existing_nullable=False)
    op.drop_column('listings', 'search_vector')
    op.drop_column('listings', 'contracted_at')
    op.drop_column('listings', 'access_policy')
    op.drop_column('listings', 'require_verified_buyer')
    op.drop_column('listings', 'require_seller_approval')
    op.drop_column('listings', 'require_proof_of_funds')
    op.drop_column('listings', 'require_identity_verification')
    op.drop_column('listings', 'require_nda')
    op.drop_column('listings', 'auction_ends_at')
    op.drop_column('listings', 'bid_count')
    op.drop_column('listings', 'current_bid')
    op.drop_column('listings', 'reserve_price')
    op.drop_column('listings', 'starting_price')
    op.drop_column('listings', 'sale_type')
    op.drop_column('buyer_profiles', 'used_unlocks_this_month')
    op.drop_column('buyer_profiles', 'monthly_unlock_limit')
    op.drop_column('buyer_profiles', 'standing_score')
    op.drop_column('buyer_profiles', 'tier')
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Payment provider (stripe, paystack, etc.)'),
    sa.Column('event_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Unique event ID from provider'),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Event type (checkout.session.completed, etc.)'),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=True, comment='Associated transaction if available'),
    sa.Column('payload_preview', sa.TEXT(), autoincrement=False, nullable=True, comment='First 1000 chars of payload for debugging'),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_webhook_events_transaction_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('webhook_events_pkey')),
    sa.UniqueConstraint('provider', 'event_id', name=op.f('uq_webhook_provider_event'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Stores processed webhook events to prevent replay attacks'
    )
    op.create_index(op.f('ix_webhook_events_transaction_id'), 'webhook_events', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_provider_event_id'), 'webhook_events', ['provider', 'event_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_processed_at'), 'webhook_events', ['processed_at'], unique=False)
    op.drop_table('disputes')
    op.drop_index('idx_data_access_status', table_name='data_access_requests')
    op.drop_table('data_access_requests')
    op.drop_table('asset_transfers')
    op.drop_table('client_representations')
    op.drop_table('user_verifications')
    op.drop_index('idx_payouts_user_id', table_name='payouts')
    op.drop_index('idx_payouts_status', table_name='payouts')
    op.drop_table('payouts')
    op.drop_table('broker_profiles')
    op.drop_index(op.f('ix_acquisition_guides_slug'), table_name='acquisition_guides')
    op.drop_table('acquisition_guides')
    # ### end Alembic commands ###
